#pragma once
#include "ARCH/I386/gdt.h"
#include "ARCH/I386/idt.h"
#include "DRIVER/vga.h"
#include "DRIVER/cursor.h"
#include "DRIVER/disk.h"
#include"DRIVER/fat.h"
#include "multiboot.h"
#include "MM/memory.h"
#include "MM/heap.h"
#include "elf.h"